estimate.settings:
  type: config_object
  label: 'Estimate settings'
  mapping:
    accepted_stage_tid:
      type: integer
      label: 'Accepted stage term ID'
    declined_stage_tid:
      type: integer
      label: 'Declined stage term ID'
