contract_residential.settings:
  type: config_object
  label: 'Contract Residential settings'
  mapping:
    work_order_autogenerate_bundles:
      type: sequence
      label: 'Work Order bundles enabled for auto-generation'
      sequence:
        type: string
        label: 'work_order bundle machine name'

    work_order_multistage_section_bundles:
      type: sequence
      label: 'Contract Section bundles eligible for multi-stage work orders'
      sequence:
        type: string
        label: 'Contract Section bundle machine name'
