<?php

/**
 * @file
 * Functions to support theming in the SASS Starterkit subtheme.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\file\Entity\File;
Use \Drupal\Core\Routing;
use Drupal\node\Entity\Node;
/**
 * Implements hook_form_system_theme_settings_alter() for settings form.
 *
 * Replace Barrio setting options with subtheme ones.
 *
 * Example on how to alter theme settings form
 */


function multi_pro_theme(&$existing, $type, $theme, $path) { 
  $hooks = array();
  $hooks['user_login_form'] = array(
   'render element' => 'form',
   'template' => 'user-login-form',
   'preprocess functions' => array(
      'multi_pro_preprocess_user_login'
   ),
  );
  $hooks['user_register_form'] = array(
   'render element' => 'form',
   'template' => 'user-register-form',
   'preprocess functions' => array(
      'multi_pro_preprocess_user_register'
   ),
  );
  $hooks['user_pass'] = array(
   'render element' => 'form',
   'template' => 'user-pass-form',
   'preprocess functions' => array(
      'multi_pro_preprocess_user_pass'
   ),
  );
  return $hooks; 
}

//Implements Hook pre process user login

function multi_pro_preprocess_user_login(&$variables){
  $variables['login_banner_title'] = theme_get_setting('login_banner_title');
  $variables['login_page_title'] = theme_get_setting('login_page_title');
  $variables['login_name_help_text'] = theme_get_setting('login_name_help_text');
  $variables['login_password_help_text'] = theme_get_setting('login_password_help_text');
  $path='';
   // Login - Banner Image
   if (theme_get_setting('login_banner_image') != Null) {
    $fid = theme_get_setting('login_banner_image')[0];
    $file =File::load($fid);
    if (!empty($file)) {
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    $variables['login_banner_image_url'] = $path;
    }
    // Login - Image
    if (theme_get_setting('login_image') != Null) {
    $fid = theme_get_setting('login_image')[0];
    $file =File::load($fid);
    if (!empty($file)) {
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    $variables['login_image_url'] = $path;
    }
  }

  //Implements hook_preprocess_user_register().

  function multi_pro_preprocess_user_register(&$variables) {
    $variables['register_banner_title'] = theme_get_setting('register_banner_title');
    $variables['register_page_title'] = theme_get_setting('register_page_title');
    $variables['register_email_help_text'] = theme_get_setting('register_email_help_text');
    $variables['register_name_help_text'] = theme_get_setting('register_name_help_text');
     // Register - Banner Image
  if (theme_get_setting('register_banner_image') != Null) {
    $fid = theme_get_setting('register_banner_image')[0];
    $file =File::load($fid);
    if (!empty($file)) {
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    $variables['register_banner_image_url'] = $path;
  }
  // Register - Image
  if (theme_get_setting('register_image') != Null) {
    $fid = theme_get_setting('register_image')[0];
    $file =File::load($fid);
    if (!empty($file)) {
      $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
    $variables['register_image_url'] = $path;
  }
  }
  
  function multi_pro_preprocess_user_pass(&$variables) {
    $variables['pass_banner_title'] = theme_get_setting('pass_banner_title');
    $variables['pass_page_title'] = theme_get_setting('pass_page_title');
    $variables['pass_email_help_text'] = theme_get_setting('pass_email_help_text');
    // Password - Banner Image
    if (theme_get_setting('pass_banner_image') != Null) {
      $fid = theme_get_setting('pass_banner_image')[0];
      $file =File::load($fid);
      if (!empty($file)) {
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
        }
      $variables['pass_banner_image_url'] = $path;
    }
    // Password - Image
    if (theme_get_setting('pass_image') != Null) {
      $fid = theme_get_setting('pass_image')[0];
      $file =File::load($fid);
      if (!empty($file)) {
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
        }
      $variables['pass_image_url'] = $path;
    }
  }

  // Implements hook_form_alter().
  function multi_pro_form_alter( &$form, &$form_state, $form_id ) {
    if ($form_id == 'user_login_form') {
      $form['name']['#attributes']['placeholder'][]='User Name *';
      $form['pass']['#attributes']['placeholder'][]='Password *';
      $form['actions']['submit']['#value'] = t('Login Now');
      $form['actions']['submit']['#attributes']['class'][]='btn btn-primary btn-style-2 btn-style-md';
    }
    if ($form_id == 'user_register_form') {
      $form['account']['mail']['#attributes']['placeholder'][]='Email *';
      $form['account']['name']['#attributes']['placeholder'][]='User Name *';
      $form['actions']['submit']['#value'] = t('Register Now');
      $form['actions']['submit']['#attributes']['class'][]='btn btn-primary btn-style-2 btn-style-md';
    }
    if ($form_id == 'user_pass') {
      $form['name']['#attributes']['placeholder'][]='User Name or Email address';
      $form['actions']['submit']['#value'] = t('Reset Now');
      $form['actions']['submit']['#attributes']['class'][]='btn btn-primary btn-style-2 btn-style-md';
    }
  }
  function multi_pro_preprocess_html(&$variables) {
    global $base_url;
    $variables['base_url'] = $base_url;
    $variables['sticky'] = theme_get_setting('sticky');
    $variables['primary_color'] = theme_get_setting('primary_color');
    $variables['secondary_color'] = theme_get_setting('secondary_color');
    $variables['show_pannel'] = theme_get_setting('show_pannel');
    $variables['loader'] = theme_get_setting('loader');
    $variables['styles'] = theme_get_setting('styles');
    // $variables['primary_colors'] = explode(',', theme_get_setting('primary_colors'));
    // $variables['secondary_colors'] = explode(',', theme_get_setting('secondary_colors'));
    $variables['header_style'] = theme_get_setting('header_style');
    $variables['styles'] = theme_get_setting('styles');
    $variables['color_set'] = ['set_1' => [
      'title' => t('color_set_1'),
      'name' => t('Combo 1'),
      'colors' => [
      'primary_color' => '#2055e4',
      'secondary_color' => '#f37272',
      ],
    ],
    'set_2' => [
      'title' => t('color_set_2'),
      'name' => t('Combo 2'),
      'colors' => [
      'primary_color' => '#1ecbe1',
      'secondary_color' => '#1ee196',
      ],
    ],
    'set_3' => [
      'title' => t('color_set_3'),
      'name' => t('Combo 3'),
      'colors' => [
      'primary_color' => '#1ecbe1',
      'secondary_color' => '#e1341e',
      ],
    ],
    'set_4' => [
      'title' => t('color_set_4'),
      'name' => t('Combo 4'),
      'colors' => [
      'primary_color' => '#ef2936',
      'secondary_color' => '#ffbf00',
      ],
    ],
    'set_5' => [
      'title' => t('color_set_5'),
      'name' => t('Combo 5'),
      'colors' => [
      'primary_color' => '#153156',
      'secondary_color' => '#1ac6ff',
      ],
    ],
    'set_6' => [
      'title' => t('color_set_6'),
      'name' => t('Combo 6'),
      'colors' => [
      'primary_color' => '#014b5f',
      'secondary_color' => '#d2a679',
      ],
    ],
    'set_7' => [
      'title' => t('color_set_7'),
      'name' => t('Combo 7'),
      'colors' => [
      'primary_color' => '#711c82',
      'secondary_color' => '#d2a679',
      ],
    ],
    'set_8' => [
      'title' => t('color_set_8'),
      'name' => t('Combo 8'),
      'colors' => [
      'primary_color' => '#111',
      'secondary_color' => '#23a7ad',
      ],
    ],
    'set_9' => [
      'title' => t('color_set_9'),
      'name' => t('Combo 9'),
      'colors' => [
      'primary_color' => '#e6565e',
      'secondary_color' => '#24cd8c',
      ],
    ],
    'set_10' => [
      'title' => t('color_set_10'),
      'name' => t('Combo 10'),
      'colors' => [
      'primary_color' => '#452e65',
      'secondary_color' => '#153156',
      ],
    ],
  ];
  $base_id="";
  $node = \Drupal::routeMatch()->getParameter('node');
  if (!empty($node)) {
  if ($variables['node_type'] === 'home_page') {
    if($node) {
      $nids = \Drupal::entityQuery('node')->accessCheck(FALSE)
              ->condition('type','home_page')->condition('status',1)->execute();
              $blog_nodes = [];
              $i=0;
              $base_id=0;
    foreach($nids as $n){
      // $blog_nodes[$n] = $i;
      $i++;
      if($node->id()==$n){
        $base_id = $i;
      }
    }
      $variables['attributes']['class'][] = 'home-' . $base_id;
    }
  }
}


  }
  //Implements preprocessor for page.
  function multi_pro_preprocess_page(&$variables){
    global $base_url;
    $variables['base_url'] = $base_url;
    //header
    $variables['header_style'] = theme_get_setting('header_style');
    $variables['sticky'] = theme_get_setting('sticky');
    $variables['loader'] = theme_get_setting('loader');
    $variables['phone'] = theme_get_setting('phone');
    $variables['phone_number'] = theme_get_setting('phone_number');
    $variables['mail'] = theme_get_setting('mail');
    $variables['button']=theme_get_setting('button');
    $variables['button_text']=theme_get_setting('button_text');
      // Search - Banner Image
    $bg_image_m_url = '';
    if (theme_get_setting('search_banner_image') != Null) {
      $fid = theme_get_setting('search_banner_image')[0];
      if (!empty($fid)) {
        $file =File::load($fid);
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
      $variables['search_banner_img_url'] = $path;
    }
    $variables['search_banner_title'] = theme_get_setting('search_banner_title');
  
  }

  //Implements preprocessor for language block.
  function multi_pro_preprocess_links__language_block(&$variables) {
    $currentLanguageCode = \Drupal::languageManager()
      ->getCurrentLanguage()
      ->getId();
    // Replace key of active language with 'activeLink'
    foreach ($variables['links'] as $i => $link) {
      /** @var \Drupal\language\Entity\ConfigurableLanguage $linkLanguage */
      $linkLanguage = $link['link']['#options']['language'];
      if ($currentLanguageCode == $linkLanguage->get('id')) {
        $variables['links']['activeLink'] = $link;
        unset($variables['links'][$i]);
      }
    }
  }
  function multi_pro_form_comment_form_alter(&$form, &$form_state, $form_id) {
    $form['subject']['widget']['#access'] = FALSE;
    $form['actions']['submit']['#value'] = t('Post Comment');
    $form['actions']['submit']['#attributes']['class'][] = 'btn-style-3 btn btn-style-sm';
    $form['actions']['preview']['#access'] = FALSE; 
  }
  function multi_pro_preprocess_comment(&$variables) {
    $comment = $variables['elements']['#comment'];
    $variables['created_time'] = $comment->getCreatedTime();
  }
  function multi_pro_preprocess_node(&$variables) {
    // Comment Count
    $nid = $variables['node']->nid->value;
    $database = \Drupal::database();
    $num_comment = $database->query('SELECT comment_count FROM {comment_entity_statistics} WHERE entity_id = ' . $nid)->fetchAssoc();
    if ($num_comment != NULL ){
    $variables['comment_count'] = $num_comment['comment_count'];
    } 
  
    /** @var \Drupal\Core\Datetime\DateFormatterInterface $formatter */
    $date_formatter = \Drupal::service('date.formatter');
    $request_time = \Drupal::time()->getRequestTime();
    $variables['posted'] = $date_formatter->formatDiff($request_time - 12345, $request_time, [
      'granularity' => 1,
      'return_as_object' => TRUE,
    ])->toRenderable();

     // PREVIOUS NODE NEXT NODE
    if ($variables['node']->getType() == 'blogs'){
    $nids = \Drupal::entityQuery('node')->accessCheck(FALSE)
              ->condition('type','blogs')->condition('status',1)->execute();
    $blog_nodes = [];
    foreach($nids as $n){
      $blog_nodes[] = $n;
    }
    $nid = $variables['node']->id();
    $key = array_search($nid, $blog_nodes);
    // Next node url
    if($nid == end($blog_nodes)){
      $data_next = Node::load($blog_nodes[0]);
    }else{
      $data_next = Node::load($blog_nodes[$key+1]);
    }
    // Prev node url
    if($nid == $blog_nodes[0]){
      $lkey = array_search(end($blog_nodes), $blog_nodes);
      $data_prev = Node::load($blog_nodes[$lkey]);
    }
    else{
      $data_prev = Node::load($blog_nodes[$key-1]);
    }
    $variables['next_url'] = $data_next->toUrl()->setAbsolute()->toString();
    $variables['prev_url'] = $data_prev->toUrl()->setAbsolute()->toString();
  }
}
  //search results
  function multi_pro_preprocess_item_list__search_results(array &$variables) {
  
    $pager = \Drupal::service('pager.manager')->getPager();
    if (!empty($pager)){
      $count_results = $pager->getTotalItems();
      $variables['total_items_count'] = $count_results;
    }
    else{
      $variables['total_items_count'] = 0;
    }
  
    $current_path = \Drupal::request()->getpathInfo();
    //echo $current_path;
    if ($current_path == '/search/node') {
      if (\Drupal::request()->query->has('keys')) {
        $keywords = \Drupal::request()->query->get('keys');
        $variables['keyword'] = $keywords;
      }
    }
    $bg_image_m_url = '';
    if (theme_get_setting('search_banner_image') != Null) {
      $fid = theme_get_setting('search_banner_image')[0];
      if (!empty($fid)) {
        $file =File::load($fid);
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
      $variables['search_banner_img_url'] = $path;
    }
    $variables['search_banner_title'] = theme_get_setting('search_banner_title');
  }
  

  // Maintenance and coming soon page   

  function multi_pro_preprocess_maintenance_page(&$variables) {
    $variables['maintenance_mode_title'] = theme_get_setting('maintenance_mode_title');
    $variables['maintenance_mode_description'] = theme_get_setting('maintenance_mode_description'); 
    $variables['background_image_maintenance'] = theme_get_setting('background_image_maintenance');
    // Maintenance - Background Image
    if (theme_get_setting('background_image_maintenance') != Null) {
      $fid = theme_get_setting('background_image_maintenance')[0];
      $file =File::load($fid);
      if (!empty($file)) {
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
      $variables['background_image_maintenance_url'] = $path;
    }
    $variables['coming_soon_title'] = theme_get_setting('coming_soon_title');
    $variables['coming_soon_description'] = theme_get_setting('coming_soon_description'); 
    // Comingsoon - Background Image
    if (theme_get_setting('background_image_coming_soon') != Null) {
      $fid = theme_get_setting('background_image_coming_soon')[0];
      $file =File::load($fid);
      if (!empty($file)) {
        $path = Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
      }
      $variables['background_image_coming_soon_url'] = $path;
    }
    $variables['mode_type'] = theme_get_setting('mode_type'); 
    $variables['date'] = theme_get_setting('date'); 
    $variables['custom_message'] = theme_get_setting('custom_message');
    $variables['#attached'] = [
        'drupalSettings' => [
            'custom_date' => $variables['custom_date'] = theme_get_setting('date'),
            'custom_message_dateExpired' => $variables['custom_message_dateExpired'] = theme_get_setting('custom_message'),
      ],
    ];
  }

  function multi_pro_preprocess_paragraph__mission_and_vision(&$vars) {                                       
    $vars['delta'] = NULL;
    foreach ($vars['paragraph']->getParentEntity()->field_mission_->getValue() as $delta => $item) {    
      if ($item['target_id'] === $vars['paragraph']->id()) {
        $vars['delta'] = $delta;
        break;
      }
    }
  }

  function multi_pro_preprocess_paragraph__question_and_answers(&$vars) {                                       
    $vars['delta'] = NULL;
    foreach ($vars['paragraph']->getParentEntity()->field_faq->getValue() as $delta => $item) {    
      if ($item['target_id'] === $vars['paragraph']->id()) {
        $vars['delta'] = $delta;
        break;
      }
    }
  }

  function multi_pro_preprocess_paragraph__current_openings(&$vars) {                                       
    $vars['delta'] = NULL;
    foreach ($vars['paragraph']->getParentEntity()->field_jobs->getValue() as $delta => $item) {    
      if ($item['target_id'] === $vars['paragraph']->id()) {
        $vars['delta'] = $delta;
        break;
      }
    }
  }
  

   