<?php

function admin_calendar_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  if ($view->id() === 'admim_wo_scheduling_calendar' && $view->current_display === 'page_month') {
    \Drupal::logger('admin_calendar')->notice('Preprocess hook fired at @time', [
      '@time' => date('H:i:s T'),
    ]);
    $rows = $variables['rows'];
    if (!empty($rows[0]['#rows'])) {
      foreach ($rows[0]['#rows'] as $index => $row) {
        $entity = $row->_entity;
        $start = $entity->get('field_scheduled_date_and_time')->value;
        $end = $entity->get('field_scheduled_date_and_time')->end_value;
        $start_dt = new \DateTime($start);
        $end_dt = $end ? new \DateTime($end) : null;
        if (!$end_dt || ($start_dt->format('H:i') === '00:00' && $end_dt->format('H:i') === '23:59')) {
          // Set on the row and the view’s event data
          $variables['rows'][0]['#rows'][$index]->allDay = TRUE;
          $variables['rows'][0]['#rows'][$index]->fullcalendar_view_all_day = TRUE; // Fullcalendar View’s key
          unset($variables['rows'][0]['#rows'][$index]->field_scheduled_date_and_time_end_value);
          \Drupal::logger('admin_calendar')->notice('Set allDay for entity: @eid, Title: @title', [
            '@eid' => $entity->id(),
            '@title' => $entity->label(),
          ]);
        }
      }
    }
  }
}