<?php

declare(strict_types=1);

use Drupal\Core\Entity\EntityInterface;

function estimate_contract_residential_entity_insert(EntityInterface $entity): void {
  if ($entity->getEntityTypeId() !== 'contract_sections') {
    return;
  }
  \Drupal::service('contract_residential.estimate_request_auto_creator')->apply($entity);
}

function estimate_contract_residential_entity_update(EntityInterface $entity): void {
  if ($entity->getEntityTypeId() !== 'contract_sections') {
    return;
  }
  \Drupal::service('contract_residential.estimate_request_auto_creator')->apply($entity);
}

/**
 * Implements hook_entity_delete().
 */
function estimate_contract_residential_entity_delete(EntityInterface $entity): void {
  if ($entity->getEntityTypeId() !== 'estimate_request') {
    return;
  }
  \Drupal::service('contract_residential.estimate_request_auto_creator')->onRequestDeleted($entity);
}
