<?php

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\FieldDefinition;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;

function sewards_hook_themer_makeid($length = 5){
  $characters = '0123456789abcdefghijklmnopqrstuvwxyz';
  $randomString = '';
  for ($i = 0; $i < $length; $i++) {
    $randomString .= $characters[rand(0, strlen($characters) - 1)];
  }
  return $randomString;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function sewards_hook_themer_form_node_form_alter(&$form, \Drupal\Core\Form\FormStateInterface &$form_state, $form_id) {
  unset($form['sewards_blockbuilder_layout']);
  unset($form['sew_shortcode']);

  $form['sew_node_settings'] = array(
    '#type'   => 'details',
    '#title'  => t('Node Settings'),
    '#group'  => 'advanced',
    '#open'   => TRUE,
    '#access' => TRUE,
    '#attributes' => array('class' => array('node-class-form')),
  );

  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  $node_id = 0;
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $node = \Drupal\node\Entity\Node::load($path_args[2]);
    if($node->id()){
      $node_id = $node->id();
    }
  }

  $form['sew_node_class']['#group']           = 'sew_node_settings';
  $form['sew_node_layout']['#group']          = 'sew_node_settings';
  $form['sew_header']['#group']               = 'sew_node_settings';
  $form['sew_box_layout']['#group']           = 'sew_node_settings';
  $form['sew_breadcrumb']['#group']           = 'sew_node_settings';
}

/**
 * Implements hook_entity_base_field_info().
 */
function sewards_hook_themer_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {

    $fields['sew_node_layout'] = BaseFieldDefinition::create('list_string')
      ->setSetting('allowed_values', [
          'fw' => 'Fullwith no sidebar (use for block builder)',
          'fw_sidebar' => 'Fullwidth width sidebar',
          'container_sidebar' => 'Container width sidebar',
          'container_no_sidebar' => 'Container no sidebar'
        ])
      ->setLabel(t('Layout settings'))
      ->setDisplayOptions('form', array(
        'type'    => 'options_select',
        'weight'  => 1,
      ))
      ->setDisplayConfigurable('form', TRUE);

    $fields['sew_breadcrumb'] = BaseFieldDefinition::create('list_string')
      ->setSetting('allowed_values', [
          'enable'    => 'Enable',
          'disable'   => 'Disable'
        ])
      ->setLabel(t('Breadcrumb settings'))
      ->setDisplayOptions('form', array(
        'type'    => 'options_select',
        'weight'  => 2,
      ))
      ->setDisplayConfigurable('form', TRUE);  

    $fields['sew_header'] = BaseFieldDefinition::create('list_string')
      ->setSetting('allowed_values', [
              'header'    => t('Header default'),
              'header-1'  => t('Header v1'),
              ])
      ->setLabel(t('Header'))
      ->setDisplayOptions('form', array(
        'type'    => 'options_select',
        'weight'  => 3,
      ))
      ->setDisplayConfigurable('form', TRUE);


    $fields['sew_node_class'] = BaseFieldDefinition::create('string')
      ->setLabel(t('CSS class(es)'))
      ->setDisplayOptions('form', array(
        'type'    => 'string_textfield',
        'weight'  => 4,
      ))
      ->setDisplayConfigurable('form', TRUE);

    
    $fields['sew_box_layout'] = BaseFieldDefinition::create('list_string')
      ->setSetting('allowed_values', [
          'boxed' => t('Boxed'),
          'boxed-v2' => t('Boxed v2'),
          'Wide'  => t('Wide')
        ])
      ->setLabel(t('Layout Box'))
      ->setDisplayOptions('form', array(
        'type'    => 'options_select',
        'weight'  => 5,
      ))
      ->setDisplayConfigurable('form', TRUE);

    return $fields;
  }
}

/**
 * Implements hook_preprocess_html().
 */
function sewards_hook_themer_preprocess_html(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  if (isset($path_args[1]) && isset($path_args[2]) && ($path_args[1] == 'node') && (is_numeric($path_args[2]))) {
    $node = \Drupal\node\Entity\Node::load($path_args[2]);
    if($node && $node->hasField('sew_node_class')){
      $class_body = $node->get('sew_node_class')->getValue();
      if(isset($class_body) && !empty($class_body[0])) {
          $variables['attributes']['class'][] = $class_body[0]['value'];
      }
    }
    if($node && $node->hasField('sew_box_layout')){
      $box_layout = $node->get('sew_box_layout')->getValue();
      if(isset($box_layout) && !empty($box_layout[0])) {
          $variables['attributes']['class'][] = $box_layout[0]['value'];
      }
    }
  }
}

function sewards_hook_themer_preprocess_page(&$variables) {
  $path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $path);
  if ($node = \Drupal::request()->attributes->get('node')) {
      if(is_object($node)){
      $variables['sew_header'] = '';
      if($node){
        
        if($node->hasField('sew_header')){
          $sew_header = $node->get('sew_header')->value;
          if($sew_header) {
            $variables['sew_header'] = $sew_header;
          }
        }

        if($node->hasField('sew_breadcrumb')){
          $sew_breadcrumb = $node->get('sew_breadcrumb')->value;
          if($sew_breadcrumb && $sew_breadcrumb == 'disable'){
            if(isset($variables['page']['breadcrumbs'])) unset($variables['page']['breadcrumbs']);
          }
        }
      }  
    }
  }
}

function sewards_hook_themer_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if($is_admin){
    $form['#attached']['library'][] = 'sewards_hook_themer/sewards_hook_themer.assets';
  }
}

function sewards_hook_themer_sliderlayer_styles_alter(&$variables){
  $variables['data'] = array(
    ''                  => 'None',
    'slide-style-1'     => 'Style 1: font-size 56px',
    'slide-style-2'     => 'Style 2: font-size 60px',
    'slide-style-3'     => 'Style 3: font-size 20px',
    'slide-style-4'     => 'Style 4: font-size 18px, background white',
    'btn-slide'         => 'Style 5: Button theme',
    'btn-slide-white'   => 'Style 5: Button white',
  );
}

function sewards_hook_themer_update_projects_alter(&$projects){
  unset($projects['sewards_hook_themer']);
}

